### ISSUE TITLE
Question - can I enable all modules

### ISSUE THREAD

**Issue by sunnysideup** [silverleague/silverstripe-ideannotator#148]
```yml

SilverLeague\IDEAnnotator\DataObjectAnnotator:
  enabled: true
  use_short_name: true
  enabled_modules:
    - app
    - sunnysideup/*
```

**Comment by Firesphere** [comment]
Since a wildcard would introduce a scan of modules, and attempt to load and instantiate all possible modules, it's quite a risk to run out of memory.
Besides that, the module can't tell the difference between a module being for Silverstripe or not.

Further, given that the module actively _alters content of files_, its behaviour can not be 100% predicted.
Adding wildcards, would mean files that are not explicitly allowed to be altered, might be touched and changed, causing possible breaking of things in all kinds of places that are hard to track down.

Third, when building the docblocks, it takes extensions etc. in to account.
This could cause strange behaviour for your modules, e.g. an extension that should only be applied to single class, may get caught up in the annotations, and you have cross-contamination of annotations.
E.g. your module "my-awesome-page-addons" might get an annotation for the extension `dnadesign\elemental\pageextension`, even though it's only in one project where you happened to use the DNA module, the remnants of it now live in another project. And will be re-build again every time.

My suggestion would be, to use a environment variable in your `.env`, that determines if a module should or should not be annotated, and give each module an annotation permission to itself.

e.g. in your `.env` file:
```dotenv
ANNOTATE_MODULES=true
```
and in every module you might want to have annotated, a `_config/annotations.yml` like so:
```yaml
---
Only:
  environment: 'dev'
  envorconstant:
     ANNOTATE_MODULES: true
---
SilverLeague\IDEAnnotator\DataObjectAnnotator:
  enabled_modules:
    - sunnysideup/my-awesome-page-addons
```

Another option would be to take the output of `composer show | grep sunnysideup`, and use the outputted list to create your enabled modules list.
